### ISSUE TITLE
ActiveSupport dependency

### ISSUE THREAD

**Issue by p-mongo** [travis-ci/gh#41]
Currently released versions of gh (0.16 and 0.17) depend on ActiveSupport 5. This makes gh incompatible with any application that uses AS 6.

In my case, my application uses `travis` which depends on `gh`. Although I do not directly use `gh` I must either use an old version of `travis` that uses pre-0.16 `gh` which does not depend on AS at all, or I cannot use AS 6 in my application.

The old versions of travis/gh use pre-1.0 faraday dependency, thus if I want to have AS 6 and faraday 1.0 in my application I am unable to figure out how to use `travis` at all.

**Comment by BanzaiMan** [comment]
#42 is merged.
